In [1]:
documents = ["I love programming", "Python is great", "I enjoy machine learning"]

In [2]:
tokens = [sentence.lower().split() for sentence in documents]

In [3]:
tokens

[['i', 'love', 'programming'],
 ['python', 'is', 'great'],
 ['i', 'enjoy', 'machine', 'learning']]

In [4]:
all_words = [[word] for sentence in tokens for word in sentence]

In [5]:
all_words

[['i'],
 ['love'],
 ['programming'],
 ['python'],
 ['is'],
 ['great'],
 ['i'],
 ['enjoy'],
 ['machine'],
 ['learning']]

# Encoding

## 1. OHE (One Hot Encoding)

In [6]:
from sklearn.preprocessing import OneHotEncoder

In [7]:
encoder = OneHotEncoder(sparse_output=False)

In [8]:
encoder.fit(all_words)

OneHotEncoder(sparse_output=False)

In [9]:
encoder.categories_

[array(['enjoy', 'great', 'i', 'is', 'learning', 'love', 'machine',
        'programming', 'python'], dtype=object)]

In [10]:
tokens

[['i', 'love', 'programming'],
 ['python', 'is', 'great'],
 ['i', 'enjoy', 'machine', 'learning']]

In [11]:
for sentence in tokens:
    print(sentence)

['i', 'love', 'programming']
['python', 'is', 'great']
['i', 'enjoy', 'machine', 'learning']


In [12]:
[[word] for word in sentence]

[['i'], ['enjoy'], ['machine'], ['learning']]

In [13]:
for sentence in tokens:
    encoded_sentence = encoder.transform([[word] for word in sentence])
    print(encoded_sentence)
    print ("\n")
    print (encoded_sentence.shape)
    print ("\n\n")

[[0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]]


(3, 9)



[[0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]]


(3, 9)



[[0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]]


(4, 9)





## 2. BoW (Bag of Words)

In [14]:
from sklearn.feature_extraction.text import CountVectorizer

In [15]:
documents = ["He loves programming", "He loves Python", "Python loves Python"]

In [16]:
bow = CountVectorizer()

In [17]:
bow_matrix =bow.fit_transform(documents)

In [18]:
print("BOW Matrix:\n", bow_matrix.toarray())

BOW Matrix:
 [[1 1 1 0]
 [1 1 0 1]
 [0 1 0 2]]


In [19]:
bow.get_feature_names_out()

array(['he', 'loves', 'programming', 'python'], dtype=object)

In [20]:
bow_matrix1 =bow.fit(documents)

In [21]:
bow_matrix1.get_feature_names_out()

array(['he', 'loves', 'programming', 'python'], dtype=object)

In [22]:
bow_matrix1.toArray()

AttributeError: 'CountVectorizer' object has no attribute 'toArray'

In [23]:
bow_matrix2 =bow.transform(documents)

In [24]:
bow_matrix2.get_feature_names_out()

AttributeError: 'csr_matrix' object has no attribute 'get_feature_names_out'

In [25]:
bow_matrix2.toarray()

array([[1, 1, 1, 0],
       [1, 1, 0, 1],
       [0, 1, 0, 2]], dtype=int64)

## 3. Term Frequency - Inverse Document Frequency (TF-IDF)

In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
documents = ["He loves programming", "He loves Python", "Python loves Python"]

In [17]:
tf_idf = TfidfVectorizer()

In [19]:
tf_idf_vector = tf_idf.fit_transform(documents)

In [20]:
tf_idf_vector.toarray()

array([[0.54783215, 0.42544054, 0.72033345, 0.        ],
       [0.61980538, 0.48133417, 0.        , 0.61980538],
       [0.        , 0.361965  , 0.        , 0.93219169]])

In [22]:
tf_idf.get_feature_names_out()

array(['he', 'loves', 'programming', 'python'], dtype=object)

## 4. Word2Vec

Neural network based approach

In [1]:
import gensim.downloader as api

In [3]:
model = api.load("word2vec-google-news-300")

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [15]:
model["man"]

array([ 0.32617188,  0.13085938,  0.03466797, -0.08300781,  0.08984375,
       -0.04125977, -0.19824219,  0.00689697,  0.14355469,  0.0019455 ,
        0.02880859, -0.25      , -0.08398438, -0.15136719, -0.10205078,
        0.04077148, -0.09765625,  0.05932617,  0.02978516, -0.10058594,
       -0.13085938,  0.001297  ,  0.02612305, -0.27148438,  0.06396484,
       -0.19140625, -0.078125  ,  0.25976562,  0.375     , -0.04541016,
        0.16210938,  0.13671875, -0.06396484, -0.02062988, -0.09667969,
        0.25390625,  0.24804688, -0.12695312,  0.07177734,  0.3203125 ,
        0.03149414, -0.03857422,  0.21191406, -0.00811768,  0.22265625,
       -0.13476562, -0.07617188,  0.01049805, -0.05175781,  0.03808594,
       -0.13378906,  0.125     ,  0.0559082 , -0.18261719,  0.08154297,
       -0.08447266, -0.07763672, -0.04345703,  0.08105469, -0.01092529,
        0.17480469,  0.30664062, -0.04321289, -0.01416016,  0.09082031,
       -0.00927734, -0.03442383, -0.11523438,  0.12451172, -0.02

In [16]:
len(model["man"])

300

In [9]:
model["i am"]

KeyError: "Key 'i am' not present"

In [17]:
model.most_similar("man")

[('woman', 0.7664011716842651),
 ('boy', 0.6824871301651001),
 ('teenager', 0.6586929559707642),
 ('teenage_girl', 0.6147903203964233),
 ('girl', 0.5921714305877686),
 ('suspected_purse_snatcher', 0.5716364979743958),
 ('robber', 0.5585119128227234),
 ('Robbery_suspect', 0.5584410429000854),
 ('teen_ager', 0.5549196600914001),
 ('men', 0.5489761233329773)]

In [14]:
model.similarity("man", "woman")

0.7664013

In [18]:
model.doesnt_match(["breakfast", "lunch", "dinner", "car"])

'car'

In [19]:
vec=model['king'] - model['man'] + model['woman']

In [21]:
model.most_similar([vec])

[('king', 0.8449392914772034),
 ('queen', 0.730051577091217),
 ('monarch', 0.6454662084579468),
 ('princess', 0.6156250834465027),
 ('crown_prince', 0.5818676948547363),
 ('prince', 0.5777117013931274),
 ('kings', 0.561366617679596),
 ('sultan', 0.5376775860786438),
 ('Queen_Consort', 0.5344247221946716),
 ('queens', 0.5289887189865112)]

### Average Word2Vec

Calculate sentence vector by taking average of word vectors

In [26]:
sentence = "I love programming"

In [27]:
words = sentence.lower().split()

In [28]:
word_vectors = [model[word] for word in words if word in model]

In [31]:
word_vectors

[array([-2.25585938e-01, -1.95312500e-02,  9.08203125e-02,  2.37304688e-01,
        -2.92968750e-02,  9.32617188e-02, -5.88378906e-02, -4.10156250e-02,
         5.22460938e-02,  2.00195312e-02, -3.44238281e-02, -2.91015625e-01,
        -2.61718750e-01, -1.90429688e-01,  3.85742188e-02,  8.30078125e-03,
         3.14941406e-02,  7.47070312e-02,  1.14746094e-01,  1.24511719e-02,
        -2.11914062e-01,  1.28906250e-01,  2.55859375e-01,  1.08886719e-01,
        -7.03125000e-02,  1.60156250e-01, -4.00390625e-01, -1.16699219e-01,
        -3.22265625e-02, -6.73828125e-02,  1.55273438e-01,  1.25000000e-01,
        -6.22558594e-02,  3.56445312e-02, -1.79687500e-01,  1.58203125e-01,
        -2.53906250e-01,  1.74804688e-01, -1.18164062e-01, -2.19726562e-03,
         1.49536133e-02, -5.71289062e-02,  2.39257812e-01,  1.36718750e-01,
         1.47460938e-01,  7.08007812e-02,  1.72851562e-01, -2.38281250e-01,
        -5.71289062e-02, -1.04492188e-01,  2.23388672e-02,  8.74023438e-02,
         1.4

In [32]:
import numpy as np

sentence_vector =  np.mean(word_vectors,axis=0)

In [33]:
sentence_vector

array([-9.65169296e-02, -5.84106445e-02,  7.38932267e-02,  2.20052078e-01,
       -4.62239571e-02,  2.99479160e-02,  1.74397781e-01, -7.99153671e-02,
       -6.00585938e-02,  1.51367188e-02, -8.23974609e-02, -1.15315758e-01,
       -2.02596024e-01, -5.33854179e-02, -7.94270858e-02,  8.28450546e-02,
        3.42610665e-02,  1.05143227e-01,  1.29964188e-01, -8.97623673e-02,
       -8.05664062e-02,  1.43717453e-01,  2.18424484e-01,  8.34960938e-02,
        4.13411446e-02, -1.43229170e-02, -8.41471329e-02,  5.37109375e-02,
        3.90625000e-03, -1.42578125e-01,  2.60416674e-03,  8.41674805e-02,
       -2.75268555e-02,  1.36230469e-01,  2.92968750e-02, -3.54817696e-02,
        2.05891933e-02,  1.51204422e-01,  1.31022139e-02,  9.96093750e-02,
        7.59480819e-02, -9.60286483e-02,  1.97753906e-01,  8.61409530e-02,
       -1.07421875e-01,  2.91341152e-02,  5.85937500e-02, -3.44238281e-02,
        2.31526699e-02,  5.69661439e-04, -6.85628280e-02, -3.36914062e-02,
       -2.49023438e-02,  

In [35]:
len(sentence_vector)

300

In [36]:
model.most_similar([sentence_vector])

[('i', 0.635019838809967),
 ('programming', 0.6342504620552063),
 ('love', 0.6172041296958923),
 ('omg_i', 0.6032937169075012),
 ('hollyrpeete_@', 0.5826165080070496),
 ('@_christineromans_@', 0.5803762078285217),
 ('i_realy', 0.5767810940742493),
 ('love_veronica_Mars', 0.5766739845275879),
 ('jonas_brothers', 0.5745945572853088),
 ('LOVE_YOU_ALL', 0.5735317468643188)]

In [37]:
model["ChatGPT"]

KeyError: "Key 'ChatGPT' not present"

### Word2Vec Custom Training

In [44]:
!uv pip install nltk

Using Python 3.11.14 environment at: env
Resolved 6 packages in 2.74s
 Downloaded nltk
Prepared 2 packages in 2.17s
Installed 2 packages in 912ms
 + click==8.3.2
 + nltk==3.9.4


In [45]:
import os
import numpy as np
import pandas as pd
import gensim
import nltk

In [47]:
nltk.download('punkt')           # sentence & word tokenizer
nltk.download('stopwords')       # common words to filter out (the, is, at...)
nltk.download('wordnet')         # word lemmatization
nltk.download('punkt_tab')       # needed in newer nltk versions (3.8+)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\sisoo\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\sisoo\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\sisoo\AppData\Roaming\nltk_data...
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\sisoo\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.


True

In [48]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [50]:
for file in os.listdir('./word2vec_training_data/'):
    print(file)

story1.txt
story2.txt


In [51]:
folder_path = r".\word2vec_training_data"

story = []

for filename in os.listdir(folder_path):
  file_path=os.path.join(folder_path,filename)

  with open(file_path, encoding='unicode_escape') as f:
    corpus=f.read()

  raw_sent=sent_tokenize(corpus)
  
  for sent in raw_sent:
    story.append(simple_preprocess(sent))

In [52]:
len(story)

44

In [53]:
story

[['once',
  'upon',
  'time',
  'there',
  'was',
  'young',
  'boy',
  'named',
  'arjun',
  'who',
  'lived',
  'in',
  'small',
  'town',
  'surrounded',
  'by',
  'hills',
  'and',
  'rivers'],
 ['he',
  'was',
  'very',
  'curious',
  'about',
  'how',
  'things',
  'worked',
  'and',
  'always',
  'asked',
  'questions'],
 ['his',
  'parents',
  'often',
  'smiled',
  'at',
  'his',
  'curiosity',
  'and',
  'encouraged',
  'him',
  'to',
  'learn',
  'more'],
 ['every',
  'day',
  'after',
  'school',
  'arjun',
  'would',
  'sit',
  'with',
  'his',
  'books',
  'and',
  'explore',
  'different',
  'topics'],
 ['he',
  'was',
  'especially',
  'fascinated',
  'by',
  'science',
  'and',
  'technology'],
 ['he',
  'wanted',
  'to',
  'understand',
  'how',
  'machines',
  'think',
  'and',
  'whether',
  'they',
  'could',
  'become',
  'as',
  'intelligent',
  'as',
  'humans'],
 ['one',
  'day',
  'while',
  'browsing',
  'through',
  'an',
  'old',
  'computer',
  'at',
  'sc

Word2Vec Model Comparison

| Feature | CBOW | Skip-gram |
|---------|------|-----------|
| Speed | Fast | Slow |
| Accuracy | Medium | High |
| Rare words | Weak | Strong |
| Data requirement | Less | More |

Architecture Comparison

| Part | CBOW | Skip-gram |
|------|------|-----------|
| Input vectors | Multiple | Single |
| Hidden layer | Average | Direct |
| Output | Single | Multiple |

In [54]:
# Custom Word2Vec model initialized for training

custom_model =gensim.models.Word2Vec(
    window=10,
    min_count=1,
    vector_size=150 
)

In [55]:
custom_model.build_vocab(story)

In [56]:
custom_model.corpus_count

44

In [57]:
custom_model.train(story, total_examples=custom_model.corpus_count, epochs=10)

(3371, 5220)

In [58]:
custom_model.wv["arjun"]

array([ 0.0025617 ,  0.00281553,  0.00667763, -0.00304704, -0.00098525,
       -0.00483486, -0.00656261, -0.00558851, -0.00093259, -0.00410921,
        0.00337374, -0.00407432,  0.00142383,  0.0004671 , -0.00249849,
       -0.00087681,  0.0066964 ,  0.00607645, -0.00317123,  0.00625151,
       -0.0039475 ,  0.00396791, -0.00167548,  0.00254897,  0.00204642,
        0.004445  , -0.00189752,  0.00562742,  0.00488234, -0.00665661,
       -0.0052223 , -0.0051106 ,  0.00169053, -0.00213649, -0.00483902,
       -0.00532992,  0.00603732,  0.00142346, -0.00622885, -0.00347193,
        0.00207329, -0.00311205,  0.00315924, -0.00295625,  0.00188825,
       -0.00539226,  0.00429895,  0.00311866,  0.00058397,  0.002016  ,
       -0.00580979,  0.00142071, -0.00068877, -0.00603753, -0.00627231,
       -0.00086464,  0.00299517,  0.00262293, -0.00438031, -0.00448252,
       -0.00351857, -0.00192492, -0.0049603 , -0.00648967, -0.00166109,
       -0.00566687, -0.00413151, -0.00406333, -0.00205244, -0.00

In [59]:
len(custom_model.wv["arjun"])

150

In [60]:
custom_model.wv["farmers"]

array([ 0.0025271 ,  0.00111317,  0.00191904,  0.00538546,  0.00442418,
        0.00240244,  0.00523134, -0.00472751,  0.00485109,  0.00278541,
       -0.00380337, -0.00278136,  0.00396342,  0.00386073, -0.00680806,
        0.00067508, -0.00021164,  0.00053407,  0.00455358, -0.00458701,
        0.00619607, -0.00627611,  0.00441338,  0.00661945, -0.00249096,
       -0.00639447,  0.00386062, -0.00618601, -0.00567506, -0.00078872,
       -0.0043589 ,  0.00581321,  0.0050518 ,  0.00029306,  0.00514941,
        0.00667842,  0.00389835,  0.00297057,  0.00364997,  0.00399388,
        0.00313769,  0.0042472 , -0.00525124,  0.00584923,  0.00563856,
        0.0061999 , -0.00586233, -0.0023642 , -0.00019196,  0.00279583,
       -0.00545618,  0.0001015 ,  0.00396681,  0.00655028, -0.00188664,
        0.00129072,  0.00428252, -0.00119235,  0.00130181, -0.00618425,
        0.00028083,  0.00268824,  0.00285098, -0.00664305, -0.0032896 ,
        0.00193203,  0.00099457, -0.00337131,  0.00350839,  0.00

In [61]:
custom_model.wv["sooriyakumar"]

KeyError: "Key 'sooriyakumar' not present"

In [62]:
custom_model.wv.most_similar("arjun")

[('important', 0.26473650336265564),
 ('books', 0.23760119080543518),
 ('to', 0.2217698097229004),
 ('on', 0.20686215162277222),
 ('explore', 0.2035728543996811),
 ('better', 0.18910065293312073),
 ('lose', 0.1785641610622406),
 ('solving', 0.1644434630870819),
 ('through', 0.16437537968158722),
 ('model', 0.16311386227607727)]

In [63]:
custom_model.wv.doesnt_match(["arjun", "engineer", "programming", "farmers"])

'farmers'

In [64]:
custom_model.wv.similarity("arjun", "engineer")

-0.008780553